#!/bin/sh

if [ -x /var/jb/usr/bin/sbreload ]; then
    /var/jb/usr/bin/sbreload >/dev/null 2>&1 || true
elif command -v sbreload >/dev/null 2>&1; then
    sbreload >/dev/null 2>&1 || true
fi

exit 0
